USE [PedSMUser]
GO

DROP TABLE IF EXISTS [Users]
GO

CREATE TABLE [dbo].[Users](
	[IDUser] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](150) NOT NULL,
	[Password] [varchar](64) NOT NULL,
	[Email] [varchar](150) NOT NULL,
	[LastLoginDate] [datetime] NULL,
	[Blocked] [bit] NOT NULL,
	[RegisterDate] [datetime] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [UserLogs]
GO

CREATE TABLE [dbo].[UserLogs](
	[IDUserLog] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[UserLogTypesID] [int] NOT NULL,
	[RegisterDate] [datetime] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUserLog] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [UserLogTypes]
GO

CREATE TABLE [dbo].[UserLogTypes](
	[IDUserLogType] [int] IDENTITY(1,1) NOT NULL,
	[Name] varchar(30) NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUserLogType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [UserNotices]
GO

CREATE TABLE [dbo].[UserNotices](
	[IDUserNotice] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[CreatedUser] [bit] NOT NULL DEFAULT 0,
	[RegisterDate] [datetime] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUserNotice] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DROP TABLE IF EXISTS [UserRecovers]
GO

CREATE TABLE [dbo].[UserRecovers](
	[IDUserRecover] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[Expired] [bit] NOT NULL DEFAULT 0,
	[Code] varchar(6) NOT NULL,
	[ExpireDate] [datetime] NOT NULL,
	[RegisterDate] [datetime] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUserRecover] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO